build:
	g++ -Wall -Wextra *.cpp  -o etapa2 -lm

run_tests: build
	./etapa2 in/test1.in
	./etapa2 in/test2.in
	./etapa2 in/test3.in
	./etapa2 in/test4.in
	./etapa2 in/test5.in
	./etapa2 in/test6.in
	./etapa2 in/test7.in
	./etapa2 in/test8.in
	./etapa2 in/test9.in
clean:
	rm -rf etapa2
